accounts/api/urls.py
from django.urls import path # access to the django url path
from .views import * # access to all the url views available
from rest_framework.routers import DefaultRouter # access to routers
from django.conf.urls import include # access to the url inclusion class

router = DefaultRouter()
router.register('userprofile', UserProfileViewset)


urlpatterns = [
    path('userprofile/get_user_profile/', GetUserProfile.as_view(), name="userprofile"), #this is to get userprofile from the users user token and session
    path('', include(router.urls)),
    path('login/', LoginView.as_view(), name="login"),
    path('authentication/logout_one/', LogoutView.as_view(), name="logout"), #this is to make sure that all the user is logged out only in that particular device
    path('userprofile/user/<int:id>/', GetUserDetails.as_view(), name="profile") #this is to get userprofile from the users models
    # and not in all the devices he has logged into
]

accounts/urls.py
from django.conf.urls import url
from .views import *



#this are urls specific to accounts

urlpatterns = [
    url(r'^login/$', UserLogin.as_view(), name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^activate/(?P<uid64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', account_activation, name='account_activation'),
]

decorona/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import Home, admin_checker
from rest_framework.urlpatterns import format_suffix_patterns
from allauth.account.views import confirm_email
from rest_framework.documentation import include_docs_urls
from rest_auth.views import PasswordResetConfirmView

urlpatterns = [
    url(r'^admin/login/', admin_checker, name="admin_checker"), 
    url(r'^admin/', admin.site.urls), #this url is linking to the django default database, to help ease development process.
    #/admin/login/

    #----this set of urls are included urls from the other apps in the website----
    #----what this does is to make sure that the urls in the other apps are properly linked to this website url
    url(r'^account/', include(('accounts.urls','accounts'), namespace='accounts')),
    url(r'^test_kit/', include(('test_kit.urls','test_kit'), namespace='test_kit')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/account/authentication/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(),
            name='password_reset_confirm'),

    #----this set of urls are the urls for this very part of the website----
    url(r'^$', Home.as_view(), name='home'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# ----this is pure django rest framework----
urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns.append(path('api/account/', include(("accounts.api.urls", "account"), namespace="account_api")))
urlpatterns.append(url(r'^api/account/authentication/registration/account-confirm-email/(?P<key>.+)/$', confirm_email, name='account_confirm_email'))
urlpatterns.append(path('api/account/authentication/', include('rest_auth.urls')))
urlpatterns.append(path('api/account/authentication/registration/', include('rest_auth.registration.urls')))
urlpatterns.append(path('api/v1/documentation/', include_docs_urls(title='DeCorona API Docs')))

test_kit/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('algorithm/<int:id>/', AlgorithmView.as_view(), name='algorithm'),
    path('algorithm/decison_box/<int:id>/', DecisionBoxView.as_view(), name='decision_box'),
    path('algorithm/connector/<int:id>/', ConnectorView.as_view(), name='connector'),

]

accounts/models.py
from __future__ import unicode_literals
from django.db import models
import uuid # access to uuid for generating reference id
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse # access to creating links that can easily be referenced as an attribute
from django.contrib.auth.models import User

User._meta.local_fields[4].__dict__['_unique'] = True
User._meta.local_fields[4].__dict__['_required'] = True

class Contact(models.Model):
    number = models.BigIntegerField() #holds the number
    country_code = models.IntegerField() #holds the country code

class Profile(models.Model):
	"""this class is responsible for the profile of each user in the website."""
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	reference_id = models.UUIDField(max_length=50, null=True, blank=True)
	phone = models.ForeignKey(Contact, null=True, blank=True, on_delete=models.SET_NULL)
	about_me = models.TextField(null=True, blank=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	class Meta:
		unique_together = ('reference_id',)#making reference key unique will allow each user to have his or her own key unique to him or her.
	def get_api_url(self):
		return reverse('account_api:userprofile', kwargs={'id':self.id})
	def get_absolute_url(self):
		return reverse('account:userprofile', kwargs={'id':self.id})

		

@receiver(post_save, sender=User)
def create_userprofile(sender, **kwargs):
     if kwargs['created']:
         user = Profile.objects.create(user=kwargs['instance'])
         user.save()
# Create your models here.

accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout
	)

class UserLoginForm(forms.Form):
	"""what this form class does is to create a form interface that can be used to login a user to the website"""
	username=forms.CharField()
	password=forms.CharField(widget=forms.PasswordInput)

class SignUpForm(UserCreationForm):
	email = forms.EmailField(required = True, help_text='Email is required', max_length=200)
	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

accounts/api/views.py
from rest_framework.views import APIView # access to the api view master class
from .serializers import * # access to all the serializers
from django.shortcuts import get_object_or_404
from django.contrib.auth import (
login as django_login,
logout as django_logout
) # access to the django login logout functions for same very purpose
from rest_framework.authtoken.models import Token # access to token for auth token assignment on login
from rest_framework.response import Response # access to the api response class
from rest_framework.authentication import TokenAuthentication, BasicAuthentication, SessionAuthentication # access to authentication classes
from rest_framework.viewsets import (
ModelViewSet, ReadOnlyModelViewSet
) # access to viewset models
from rest_framework.mixins import (
ListModelMixin, CreateModelMixin, DestroyModelMixin,
RetrieveModelMixin, UpdateModelMixin,
)
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import (
IsAuthenticated,IsAuthenticatedOrReadOnly
) # access to the built-in permission classes
from .permissions import * # access to custom permission classes
from rest_framework.decorators import action # access to the some decorator functions

class UserProfileViewset(ReadOnlyModelViewSet):
    serializer_class = UserProfileSerializer
    queryset = Profile.objects.filter(user__is_active=True)
    def get_serializer_class(self):
        if self.action=='list':
            return UserProfileListSerializer
        else:
            return UserProfileSerializer
    def update(self, request, *args, **kwargs):
        return ModelViewSet.update(self, request, *args, **kwargs)
    def get_permissions(self):
        if self.action=='list':
            permission_classes = [IsAuthenticatedOrReadOnly(),]
        else:
            permission_classes = [IsOwnerOrReadOnly(),]
        return permission_classes
   
class GetUserProfile(APIView):
    # serializer_class = UserProfileUpdateSerializer
    # queryset=Image.objects.all()
    lookup_field='id'
    permission_classes = [IsOwnerOrSuperUserOrReadOnly]
    def get(self, request):
        if not request.user.is_authenticated:
            return Response({'details':'you are not logged in'}, status=300)
        profile = request.user.profile
        serializer = UserProfileSerializer(profile)
        return Response(serializer.data, status=200)

    def put(self, request):
        if not request.user.is_authenticated:
            return Response({'details':'you are not logged in'}, status=300)
        profile = request.user.profile
        serializer = UserProfileUpdateSerializer(data=request.data, instance=profile)
        if serializer.is_valid():
            serializer.save()
        return Response(serializer.data, status=200)

    def patch(self, request):
        if not request.user.is_authenticated:
            return Response({'details':'you are not logged in'}, status=300)
        profile = request.user.profile
        serializer = UserProfileUpdateSerializer(data=request.data, instance=profile)
        if serializer.is_valid():
            serializer.save()
        return Response(serializer.data, status=200)


class GetUserDetails(APIView):
    def get(self, request, id=None):
        user = get_object_or_404(User, id=id)
        profile = Profile.objects.get(user=user)
        serializer = UserProfileSerializer(profile)
        return Response(serializer.data, status=200)


class LoginView(APIView):
    """
    This class does not check for somethings to log someone in an alternative
    is to use django rest auth login api view or make a custom api view that puts
    that into consideration
    """
    def post(self, request):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        django_login(request, user)
        token, created = Token.objects.get_or_create(user=user)
        return Response({"token":token.key}, status=200)

class LogoutView(APIView):
    authentication_classes = [TokenAuthentication,]
    def post(self,request):
        django_logout(request)
        return Response({"details":"successfully logged out"}, status=200)

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token import account_activation_token
from .forms import *
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout
	)


def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST or None)
		if form.is_valid():
			user = form.save(commit=False)
			user.is_active = False
			user.save()
			current_site = get_current_site(request)
			mail_caption = 'DeCorona Account Activation'
			message = render_to_string('accounts/account_activation_email.html', {
				'user':user,
				'domain':current_site,
				'uid': force_text(urlsafe_base64_encode(force_bytes(user.pk))),
				'token':account_activation_token.make_token(user),
				})
			to_email = form.cleaned_data.get('email')
			other_email = 'snappynolwac@gmail.com'
			email = EmailMessage(
				mail_caption, message, to=[to_email, other_email]
				)
			try:
				email.send()
			except:
				user.is_active = True #change this later because this activates the users account because email sending failed, meanwhile the are other reasons why email sending could fail
				user.save()
				return HttpResponseRedirect('/account/login/')
			return render(request, 'accounts/registration_form_done.html', {'user':user, 'site':current_site})
	form = SignUpForm()
	return render(request, 'accounts/signup.html', {'form':form})
def account_activation(request, uid64, token):
	"""This is just to activate the a user account. Account activation and email confirmation is just to make sure that the user
	did not provide an invalid email during registration and that the email belongs to the user"""
	try:
		uid = force_text(urlsafe_base64_decode(uid64))
		user = User.objects.get(pk = uid)
	except (TypeError, ValueError, OverflowError, User.DoesNotExist):
		user = None
	if user is not None and account_activation_token.check_token(user, token):
		user.is_active = True
		user.save()
		login(request, user)
		return render(request, 'accounts/account_activation_done.html', {'user':user})
	else:
		return render(request, 'accounts/bad_activation.html', {})

def user_logout(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect('/')
	logout(request)
	return HttpResponseRedirect('/')

#---below is for class views ----

class UserLogin(View):
	"""this class takes care of login and logout"""
	def get(self, request):
		if request.user.is_authenticated:
			return HttpResponseRedirect('/')
		context = {
		}
		return render(request, 'accounts/login.html', context)
	def post(self, request):
		if request.user.is_authenticated:
			return HttpResponseRedirect('/')
		form = UserLoginForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			#userprofile = Profile.objects.create(user=instance.user, reference_id=get_reference_id(),)
			username=form.cleaned_data.get("username")
			password=form.cleaned_data.get("password")
			user = authenticate(username=username, password=password)
			if user is not None and user.is_active:
				login(request, user)
				return HttpResponseRedirect('/')
		return HttpResponseRedirect('/')

accounts/templates/accounts/account_activation_done.html
{% extends 'accounts/base.html'%}
{%block content%}
<div class="uk-container">
	<div class="uk-position-center">
		<h2>Congratulations! {{user.username}}</h2>
		<p style="color:lightgreen;">your account is now active. You can now perform any of the activities on the website. For any Question kindly send us a contact message or open a support ticket for the particular problem that you may have</p>
		<p>Use the form below to complete your user profile. You can add a profile Picture of your choice and also add some information about yourself.</p>
		<form id="userprofile_form" method="POST" action="" enctype="multipart/form-data">
			<legend>PROFILE FORM</legend>
			<div class="uk-margin">
				<input type="text" name="">
			</div>
		</form>
	</div>
</div>
{%endblock%}

accounts/templates/accounts/account_activation_email.html
{%load staticfiles%}
{% autoescape off %}
<div class="uk-container">
	<div>
		<div class="banner uk-position-center" style="width: 90%;min-height: 200px;">
			<img class="uk-cover" uk-position-cover="" src="{%static 'images/light.png'%}">
		</div>
	</div>
	<div class="uk-card uk-card-body">
		Congratulation! <h3 class="uk-card-title" style="color: lightgreen;"><strong>{{user.username}}</strong></h3>
		Please click on the link below to have your account activated.
		http://{{domain}}{%url 'accounts:account_activation' uid64=uid token=token%}
	</div>
	
</div>

{% endautoescape %}

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{%block title%}DeCorona{%endblock%}</title>
	{%load staticfiles%}
	{%block websiteicon%}<link rel="icon" type="image/jpg" href="{%static 'img/logo.jpg'%}"/>{%endblock%}
    <meta charset="utf-8">
    {%block viewport%}<meta name="viewport" content="width=device-width, initial-scale=1.0">{%endblock%}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="content-language" content="en-us, en-bre"/>
    <!-- this is specifically targetted for facebook, instagram and whatsapp -->
    {%block metafacebook%}
    <meta property="og:type" content="website"/>
    <meta property="og:description" content="Your number one guide in a period of disease outbreak" />
    <meta property="og:url" content="{{request.build_absolute_uri}}"/>
    {%if instance.images.first%}
    <meta property="og:image" content="{{instance.images.first.image.url}}"/>
    {%else%}
    <meta property="og:image" content="{%static 'img/logo.jpg'%}"/>
    {%endif%}
    {%endblock%}

    <!-- facebook and whatsapp specific ends here -->
    {%block meta%}
    <meta name="description" content="Your number one guide in a period of disease outbreak"/>
    <meta name="abstract" content="Your number one guide in a period of disease outbreak"/>
    <meta name="Keywords" content="Coronavirus covid19 covid corona virus outbreak pandemic">
    {%endblock%}
	{%block staticfile%}
		<script type="text/javascript" src="{%static 'uikit-icons.min.js'%}"></script>
		<script type="text/javascript" src="{%static 'all.js'%}"></script>
		<link type="text/css" rel="stylesheet" href="{%static 'style.css'%}"  />
		<style type="text/css">
			.navbar{
				background-color: black;
			}
		</style>
	{%endblock%}
	{%block included_staticfiles%}
	{%endblock%}
</head>
<body>

{%block body%}
{%block navbar%}
<nav class="navbar" style="background-color: black; position: static;">
    <div class="nav-wrapper">
    <!-- Navbar Logo -->
      <div>
      <!-- Logo Placeholder for Inlustration -->
      <a href="/"><img src="{%static 'img/logo.jpg'%}" class="logo" /></a>
      </div>

    <!-- Navbar Links -->
	    <ul>
	      <!-- <li><a href="#home">Home</a></li>
	     <li><a href="#services">Services</a></li>     <li><a href="#about">About</a></li> -->
	     	{%if not request.user.is_authenticated%}
			<li><a href="/account/login">Login</a></li>
	     	<li><a href="/account/signup" >Sign Up</a></li>
			{%endif%}
			{%if request.user.is_authenticated%}
			<li><a href="/accounts/logout">Logout</a></li>
			{%endif%}
	    </ul>
    </div>
  </nav>
{%endblock%}
<!-- <br/> <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/> -->
<!-- ======HERO SECTION STARTS===== -->

{%block content%}
	{%block headerhero%}
	<div class="hero-image">
		<div class="herorow">
	  <div class="herocolumn heroleft">
	    <!-- <h2>Column 1</h2>
	    <p>Some text..</p> -->
	  </div>
	  <div class="herocolumn heroright">
	    <h3 style="color: white;">CHOOSE AN OPTION</h3>
	    <ul>
	  	<li><a href="#"> Check Spread rate</a></li>
	  	<li><a href="{%url 'test_kit:algorithm' 1%}"> Take COVID-19 Test</a></li>
	  	{%if not request.user.is_staff%}
	  		<li><a href="#" id="customer_care"> Speak to a doctor (Live Chat)</a></li>
	  	{%endif%}
		</ul>
	  </div>
	</div>
	  <!-- <div class="hero-text">
	    <h1 style="font-size:50px">I am John Doe</h1>
	    <p>And I'm a Photographer</p>
	    <button>Hire me</button>
	  </div> -->
	</div>
	{%endblock%}

<!-- ======  FLEX SECTION STARTS======= -->
	{%block chat%}
		{%load channels_chat_tags%}
		{%chat_box request%}
	{%endblock%}

<div class="flex-container">
  <div>40
  	<div><p>Cases</p></div>
  </div>
  <div>20
  	<div><p>Tested</p></div>
  </div>
  <div class="positive">10
  	<div><p>Positive</p></div>
  </div>  
  <div class="dead">1
  	<div><p>Dead</p></div>
  </div>  
</div>

<!-- ======  FLEX SECTION ENDS ======= -->

<div class="servinfo"> <p>FIND SERVICES AND INFORMATION</p></div>

<div class="mycontainer">
  <div>ABOUT COVID-19</div>
  <div>GET ASSISTANCE</div>
  <div>HOSPITALS</div>  
  <div>EMERGENCY</div>  
</div>

<div class="servinfo"> <p>LIVE UPDATES AROUND THE GLOBE</p></div>

<div class="lupdates">
  <div><p>We are dedicated to serving you</p></div>
  <div><p>We give you  the hint you need to survive any  disease outbreak</p></div>  
</div>

<br>

<div class="myrow">
  <div class="mycolumn">
    <img src="{%static 'img/logo.jpg'%}" class="foologo">
    <p><a href="mailto:desars19@gmail.com">desars19@gmail.com</a></p>
    <p><a href="tel:08107905404">Call: 08107905404</a></p>
  </div>
  <div class="mycolumn">
    <h3 style="color: white;">Social Handles</h3>
    <p><a href="https://facebook.com/DeCorona19"> Facebook</a></p>
    <p><a href="https://twitter.com/DeCorona8"> Twitter</a></p>
    <p><a href="https://instagram.com/de.sars"> Instagram</a></p>
  </div>
  <div class="mycolumn">
    <h2 style="color: white;">Take Action</h2>
    {%if not request.user.is_staff%}
    <p><a href="{%url 'test_kit:algorithm' 1%}"> Use COVID-19 Test Kit</a></p>
    {%endif%}
    <p><a href="#"> About Us</a></p>
    {%if not request.user.is_authenticated%}
    <p><a href="/account/login"> Login</a> | <a href="#"> Register</a></p>
    {%endif%}
  </div>
</div>
{%endblock%}
{%endblock%}
</body>
<link type="text/css" rel="stylesheet" href="{%static 'style.css'%}"  />
</html>

accounts/templates/accounts/chart.html
{%load staticfiles%}
<script type="text/javascript" src="{%static 'chart.min.js'%}"></script>
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

var ctx2 = document.getElementById('myChart2').getContext('2d');
var mychart2 = new Chart(ctx2,{
    type: 'polarArea',
    data: {
        labels: ['yellow', 'greeen', 'blue', 'pink', 'white'],
        datasets: [{
            label: 'the impact of color on websites', 
            data: [10, 20, 45, 60, 70],
            backgroundColor: [
            'rgba(200, 200, 200, 0.2)',
            'rgba(200, 100, 60, 0.2)',
            'rgba(200, 20, 200, 0.2)',
            'rgba(100, 200, 200, 0.2)',
            'rgba(20, 200, 100, 0.2)',
            ],
            borderColor: [
            'rgba(200, 200, 200, 0.2)',
            'rgba(200, 100, 60, 0.2)',
            'rgba(200, 20, 200, 0.2)',
            'rgba(100, 200, 200, 0.2)',
            'rgba(20, 200, 100, 0.2)',
            ],
            borderWidth: 1
        }]
    },
    options:{
        scales:{
            yAxes:[{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
{% extends 'accounts/base.html'%}
{%load staticfiles%}
	<title>DeCorona</title>
	<link rel="stylesheet" type="text/css" href="{%static 'uikit.min.css'%}">
<style type="text/css">
</style>
{%block included_staticfiles%}
	<script type="text/javascript" src="{%static 'uikit.min.js'%}"></script>
	<link rel="stylesheet" type="text/css" href="{%static 'uikit.min.css'%}">
	
{%endblock%}
</head>
<body>
{%block content%}
<div class="uk-flex uk-flex-center" style="height:100vh;width:100%;">
{% load account_tags %}
{%login 'DeCorona Login'%}
<style type="text/css">
		html{
			background-color: lightgrey;
		}
	</style>
</div>
{%endblock%}
</body>
<script type="text/javascript" src="{%static 'uikit.min.js'%}"></script>
</html>

accounts/templates/accounts/login_template.html
{%load staticfiles%}
{%block included_staticfiles%}
	<link rel="stylesheet" type="text/css" href="{%static 'uikit.min.css'%}">
{%endblock%}
<div class="uk-card uk-flex uk-flex-center uk-card-body uk-width-medium  uk-margin-auto-vertical" style="background-color:#3ac793;">
	<form action="{{login_url}}" method="post"  enctype="multipart/form-data">
		{% csrf_token %}
	    <fieldset class="uk-fieldset">

	        <legend class="uk-legend uk-button-text" style="color:white;">{{title}}</legend>
	        <hr class="uk-divider-icon">
	        <div class="uk-margin">
	            <input class="uk-input" type="text" placeholder="username" name="username">
	        </div>
	        <div class="uk-margin">
	            <input class="uk-input" type="password" placeholder="password" name="password">
	        </div>
	        <hr class="uk-divider-icon">
	        <input class="uk-button uk-button-primary" type="submit" value="Submit" uk-button="">

	    </fieldset>
	</form>
</div>

accounts/templates/accounts/registration_form_done.html
{% extends 'accounts/base.html'%}
{%load staticfiles%}
{%block included_staticfiles%}
	<link rel="stylesheet" type="text/css" href="{%static 'uikit.min.css'%}">
{%endblock%}
{%block content%}
<div class="uk-container">
	<div class="uk-position-center">
		<h2>Congratulations! {{user.username}}</h2>
		<p style="color:lightgreen;">You have one more step to completing your registration</p>
		<p>Please Verify your email account to complete the registration process</p>
	</div>
</div>
{%endblock%}

accounts/templates/accounts/signup.html
{% extends 'accounts/base.html'%}
{%load staticfiles%}
{%block included_staticfiles%}
	<link rel="stylesheet" type="text/css" href="{%static 'uikit.min.css'%}">
{%endblock%}
{%block navbar%}{%endblock%}
{%block body%}
<style type="text/css">
	
	html{background-color: lightgrey;}
</style>
<div class="uk-flex uk-flex-center">
<div class="uk-card uk-flex uk-flex-center uk-card-body  uk-margin-auto-vertical" style="background-color:white;">
	<form action="{%url 'accounts:signup' %}" method="post"  enctype="multipart/form-data">
		{% csrf_token %}
	    <fieldset class="uk-fieldset">
	    	<legend>DeCorona SignUp</legend>
	    	<hr class="uk-divider-icon">
			<div class="uk-margin">
				<input class="uk-input" placeholder="Username" type="text" name="username" autofocus required id="id_username" maxlength="150" /><br />
				<span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
			</div>
			<div class="uk-margin">
				<input class="uk-input" placeholder="Email" type="email" name="email" required id="id_email" maxlength="200" /><br />
				<span class="helptext">Email is required</span>
			</div>
			<div class="uk-margin">
				<input class="uk-input" placeholder="Password" type="password" name="password1" required id="id_password1" /><br>
				<span class="helptext">
					<ul class="uk-text-danger">
						<li class="uk-text-danger">Your password can't be too similar to your other personal information.</li>
						<li>Your password must contain at least 8 characters.</li>
						<li>Your password can't be a commonly used password.</li>
						<li>Your password can't be entirely numeric.</li>
					</ul>
				</span>	
			</div>
			<div class="uk-margin">
				<input class="uk-input" placeholder="Confirm Password" type="password" name="password2" required id="id_password2" /><br />
				<span class="helptext">Enter the same password as before, for verification.</span>
			</div>
			<hr class="uk-divider-icon">
	        <input class="uk-button uk-button-primary" type="submit" value="Submit" uk-button="">

	    </fieldset>
	</form>
</div>
</div>
{%endblock%}
{%block bottom_navbar%}{%endblock%}